import { Link, useLocation } from 'wouter';
import { Show, useClerk } from '@clerk/react';
import { ArrowRight, ArrowUpRight, CalendarDays, MapPin, Menu, X, Activity } from 'lucide-react';
import { useState } from 'react';
import { useHealthCheck, useGetPlatformSettings, type Event } from '@workspace/api-client-react';

export const dateLabel = (value: string) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
export const timeLabel = (value: string) => new Date(value).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
export const elapsed = (ms: number) => { const m = Math.floor(ms / 60000); const s = Math.floor((ms % 60000) / 1000); return `${m}:${String(s).padStart(2, '0')}.${String(Math.floor(ms % 1000 / 10)).padStart(2, '0')}`; };
export const errorMessage = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.';
export function Brand({ inverse = false }: { inverse?: boolean }) {
  return <Link href="/" data-testid="link-home" className={`inline-flex items-center gap-2.5 leading-none ${inverse ? 'text-[#f7f1df]' : 'text-[#173e3d]'}`}><span className={`w-9 h-9 flex items-center justify-center border-[3px] rounded-full ${inverse ? 'border-[#f8ba35]' : 'border-[#c44a2d]'}`}><span className="w-2 h-2 rounded-full bg-[#c44a2d]" /></span><span className="display text-[28px] tracking-tight">BEER<span className="text-[#c44a2d]">MILE</span><small className="block font-sans text-[8px] font-black tracking-[.26em] leading-[1.8]">TRACKER / EST. NOW</small></span></Link>;
}
export function Header() {
  const [location] = useLocation();
  const { signOut } = useClerk();
  const [open, setOpen] = useState(false);
  const nav = [{ href: '/events', label: 'Find a race' }, { href: '/join', label: 'Enter a code' }];
  return <header className="relative z-20 border-b border-[#173e3d]/20 bg-[#f6f0df]">
    <div className="shell h-[76px] flex items-center justify-between gap-6">
      <Brand />
      <nav className="hidden md:flex items-center gap-9">{nav.map(n => <Link key={n.href} href={n.href} data-testid={`link-${n.label.toLowerCase().replaceAll(' ','-')}`} className={`eyebrow transition-colors hover:text-[#c44a2d] ${location === n.href ? 'text-[#c44a2d]' : ''}`}>{n.label}</Link>)}</nav>
      <div className="hidden md:flex items-center gap-3"><Show when="signed-out"><Link href="/sign-in" data-testid="link-sign-in" className="btn btn-outline">Sign in</Link><Link href="/sign-up" data-testid="link-sign-up" className="btn btn-primary">Get on the line <ArrowUpRight size={15}/></Link></Show><Show when="signed-in"><Link href="/dashboard" data-testid="link-dashboard" className="btn btn-primary">My dashboard <ArrowUpRight size={15}/></Link><button data-testid="button-sign-out" className="btn btn-outline" onClick={() => signOut({redirectUrl: import.meta.env.BASE_URL})}>Sign out</button></Show></div>
      <button data-testid="button-menu" className="md:hidden p-2" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button>
    </div>
    {open && <nav className="md:hidden shell py-5 border-t border-[#173e3d]/20 flex flex-col gap-5">{nav.map(n => <Link key={n.href} href={n.href} onClick={() => setOpen(false)} data-testid={`link-mobile-${n.href.slice(1)}`} className="eyebrow">{n.label}</Link>)}<Show when="signed-out"><Link href="/sign-in" onClick={() => setOpen(false)} className="eyebrow">Sign in</Link><Link href="/sign-up" onClick={() => setOpen(false)} className="eyebrow">Create account</Link></Show><Show when="signed-in"><Link href="/dashboard" onClick={() => setOpen(false)} className="eyebrow">Dashboard</Link><button onClick={() => signOut({redirectUrl: import.meta.env.BASE_URL})} className="eyebrow text-left">Sign out</button></Show></nav>}
  </header>;
}
export function Footer() {
  const health = useHealthCheck({ query: { queryKey: ['/api/healthz'], retry: 1, refetchInterval: 60000 } });
  const settings = useGetPlatformSettings();
  return <footer className="bg-[#173e3d] text-[#f6f0df] mt-auto"><div className="shell py-12 md:py-16 grid md:grid-cols-[1fr_auto] gap-12"><div><Brand inverse/><p className="mt-5 max-w-sm text-sm text-[#f6f0df]/65">Four laps. Four pours. One time that tells the whole story.</p></div><div className="flex gap-14 flex-wrap"><div><div className="eyebrow text-[#f8ba35] mb-5">Explore</div><div className="grid gap-3 text-sm"><Link href="/events">All races</Link><Link href="/join">Private race</Link><Link href="/dashboard">Your dashboard</Link></div></div><div><div className="eyebrow text-[#f8ba35] mb-5">Take it with you</div><div className="grid gap-3 text-sm">{settings.data?.appStoreIosUrl && <a href={settings.data.appStoreIosUrl} target="_blank" rel="noreferrer">iOS app ↗</a>}{settings.data?.playStoreAndroidUrl && <a href={settings.data.playStoreAndroidUrl} target="_blank" rel="noreferrer">Android app ↗</a>}{!settings.data?.appStoreIosUrl && !settings.data?.playStoreAndroidUrl && <span className="text-[#f6f0df]/55">Race-day access, right here.</span>}</div></div></div></div><div className="shell border-t border-[#f6f0df]/20 py-5 flex justify-between gap-4 text-[10px] uppercase tracking-widest text-[#f6f0df]/55"><span>© {new Date().getFullYear()} Beer Mile Tracker</span><span data-testid="status-service">{health.isError ? 'Connection interrupted' : health.isLoading ? 'Checking service' : 'Timing service online'} <Activity size={11} className="inline ml-1"/></span></div></footer>;
}
export function Page({children}: {children: React.ReactNode}) { return <div className="min-h-[100dvh] flex flex-col"><Header/><main className="flex-1">{children}</main><Footer/></div>; }
export function SectionHead({kicker,title,aside}: {kicker:string;title:string;aside?:React.ReactNode}) { return <div className="flex justify-between items-end gap-5 mb-8"><div><div className="eyebrow text-[#c44a2d] mb-3">{kicker}</div><h2 className="display text-5xl md:text-7xl">{title}</h2></div>{aside}</div>; }
export function EventCard({event,index=0}: {event:Event;index?:number}) { return <Link href={`/events/${event.id}`} data-testid={`card-event-${event.id}`} className="event-card panel block overflow-hidden group"><div className="h-2 bg-[#c44a2d] group-hover:bg-[#f8ba35] transition-colors"/><div className="p-6 md:p-8"><div className="flex justify-between gap-4 items-start"><span className="eyebrow text-[#c44a2d]">{String(index+1).padStart(2,'0')} / {event.status === 'active' ? 'Live now' : event.status}</span><ArrowUpRight size={20} className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform"/></div><h3 className="display text-[42px] md:text-[54px] mt-8 mb-7 leading-[.88]">{event.title}</h3><div className="rule pt-5 flex flex-col gap-2.5 text-sm font-semibold"><span className="flex items-center gap-2"><CalendarDays size={16} className="text-[#c44a2d]"/>{dateLabel(event.eventDate)} · {timeLabel(event.eventDate)}</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#c44a2d]"/>{event.locationName || 'Location TBA'}</span></div></div></Link>; }
export function SkeletonRows() { return <div className="space-y-4" aria-label="Loading"><div className="skeleton h-20"/><div className="skeleton h-20"/><div className="skeleton h-20"/></div>; }
export function StatePanel({title,detail,action}: {title:string;detail:string;action?:React.ReactNode}) { return <div className="panel p-10 md:p-16 text-center"><div className="mx-auto mb-6 w-14 h-14 rounded-full border-4 border-[#c44a2d] flex items-center justify-center"><span className="w-3 h-3 bg-[#f8ba35] rounded-full"/></div><h3 className="display text-4xl md:text-5xl">{title}</h3><p className="text-sm text-[#68736b] mt-4 max-w-sm mx-auto">{detail}</p>{action && <div className="mt-7">{action}</div>}</div>; }
export function InlineError({error,retry}: {error:unknown;retry?:()=>void}) { return <div role="alert" className="border-l-4 border-[#c44a2d] bg-[#fae8df] p-5 text-sm"><strong>That didn’t go through.</strong> {errorMessage(error)} {retry && <button data-testid="button-retry" className="font-bold underline ml-2" onClick={retry}>Try again</button>}</div>; }
export function ArrowLink({href,children}: {href:string;children:React.ReactNode}) { return <Link href={href} className="btn btn-primary" data-testid={`link-${href.replaceAll('/','-')}`} >{children}<ArrowRight size={16}/></Link>; }