import { useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { Show } from '@clerk/react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, ChevronDown, Clock3, MapPin, Radio, Search, Trophy, Users } from 'lucide-react';
import { useListEvents, useGetEvent, useGetLeaderboard, useCreateRegistration, useJoinEventByCode, getGetEventQueryKey, getGetLeaderboardQueryKey, getListRegistrationsQueryKey, type Event } from '@workspace/api-client-react';
import { Page, SectionHead, EventCard, SkeletonRows, StatePanel, InlineError, ArrowLink, dateLabel, timeLabel, elapsed } from '@/components/race-ui';

const isPublic = (event: Event) => event.status === 'open' || event.status === 'active' || event.status === 'completed';
export function HomePage() {
  const events = useListEvents();
  const upcoming = (events.data || []).filter(e => (e.status === 'open' || e.status === 'active') && new Date(e.eventDate).getTime() >= Date.now() - 86400000).sort((a,b) => +new Date(a.eventDate) - +new Date(b.eventDate)).slice(0,3);
  return <Page>
    <section className="relative overflow-hidden bg-[#c44a2d] text-[#f8f1df] min-h-[580px] md:min-h-[650px] flex items-center"><div className="track-lines absolute inset-0 opacity-80"/><div className="shell relative w-full py-20 md:py-28"><div className="max-w-[1040px] fade-in"><div className="eyebrow mb-7 inline-flex items-center gap-3 bg-[#173e3d] px-4 py-3 text-[#f8ba35]"><span className="w-2 h-2 rounded-full bg-[#f8ba35] animate-pulse"/> THE RACE IS ON</div><h1 className="display text-[clamp(82px,13.4vw,210px)] leading-[.75]">FOUR LAPS.<br/><span className="text-[#f8ba35]">FOUR POURS.</span><br/>NO EXCUSES.</h1><div className="mt-10 md:mt-14 flex flex-col md:flex-row md:items-end justify-between gap-7"><p className="text-lg md:text-xl max-w-md font-medium leading-relaxed">Find your start line, follow the field, and make every split count. This is beer mile, down to the second.</p><div className="flex flex-wrap gap-3"><Link href="/events" data-testid="link-explore-races" className="btn btn-light">Explore races <ArrowUpRight size={17}/></Link><Link href="/join" data-testid="link-enter-race-code" className="btn border border-[#f8f1df] text-[#f8f1df]">Have a code? <ArrowRight size={17}/></Link></div></div></div></div><div className="absolute right-0 top-0 hidden lg:block rotate-90 origin-top-right translate-y-16 -translate-x-5 eyebrow opacity-65">CHUG / RUN / REPEAT / 2026</div></section>
    <div className="bg-[#173e3d] text-[#f6f0df]"><div className="shell flex flex-wrap justify-between gap-4 py-5 eyebrow"><span>01 / The starting line</span><span className="text-[#f8ba35]">Official race-day timing</span><span>04 laps · 01 mile · 01 finish</span></div></div>
    <section className="shell py-20 md:py-28"><SectionHead kicker="Upcoming / Open for entry" title="Find your line." aside={<Link href="/events" className="hidden sm:inline-flex items-center gap-2 eyebrow hover:text-[#c44a2d]">View all races <ArrowUpRight size={17}/></Link>}/>{events.isLoading ? <SkeletonRows/> : events.isError ? <InlineError error={events.error} retry={() => events.refetch()}/> : upcoming.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{upcoming.map((e,i) => <EventCard event={e} index={i} key={e.id}/>)}</div> : <StatePanel title="The track is quiet. For now." detail="No public races are open at the moment. Check back soon, or enter an event code if you've been invited." action={<ArrowLink href="/join">Enter a race code</ArrowLink>}/>}</section>
    <section className="bg-[#e9dfc8] py-20 md:py-28"><div className="shell grid lg:grid-cols-[.8fr_1.2fr] gap-12 lg:gap-20 items-center"><div><div className="eyebrow text-[#c44a2d] mb-5">The format / 01—04</div><h2 className="display text-[clamp(64px,8vw,120px)]">SIMPLE<br/>RULES.<br/><span className="text-[#c44a2d]">HARD MILE.</span></h2></div><div className="grid gap-0 border-t border-[#173e3d]/30">{[['01','POUR','Start each lap with a beer. Get it down before you get moving.'],['02','RUN','One quarter-mile lap. Find a rhythm. Try to keep it.'],['03','REPEAT','Do it four times. Every split is logged and every place is earned.'],['04','FINISH','Cross the line. See where you stand as results land live.']].map(([num,heading,copy]) => <div key={num} className="grid grid-cols-[48px_125px_1fr] gap-3 py-6 border-b border-[#173e3d]/30 items-start"><span className="mono text-[#c44a2d] text-sm">{num}</span><strong className="display text-3xl">{heading}</strong><p className="text-sm leading-relaxed text-[#465e58]">{copy}</p></div>)}</div></div></section>
    <section className="bg-[#f8ba35] overflow-hidden"><div className="shell py-20 md:py-28 grid md:grid-cols-[1fr_auto] gap-8 items-end"><div><div className="eyebrow mb-5">For the ones who make race day happen</div><h2 className="display text-[clamp(58px,8vw,120px)] max-w-4xl">YOUR RACE.<br/>YOUR RULES.<br/><span className="text-[#c44a2d]">EVERY SECOND.</span></h2><p className="mt-7 max-w-lg text-lg font-medium">Open registration. Confirm your field. Watch the leaderboard take shape in real time.</p></div><Show when="signed-out"><Link href="/sign-up" className="btn btn-dark self-end">Create an account <ArrowUpRight size={17}/></Link></Show><Show when="signed-in"><Link href="/dashboard" className="btn btn-dark self-end">Go to dashboard <ArrowUpRight size={17}/></Link></Show></div></section>
  </Page>;
}
export function EventsPage() {
  const events = useListEvents(); const [term,setTerm] = useState(''); const [filter,setFilter] = useState('upcoming');
  const items = (events.data || []).filter(e => isPublic(e)).filter(e => filter === 'all' || (filter === 'upcoming' ? e.status === 'open' || e.status === 'active' : e.status === 'completed')).filter(e => `${e.title} ${e.locationName || ''}`.toLowerCase().includes(term.toLowerCase())).sort((a,b) => filter === 'past' ? +new Date(b.eventDate)-+new Date(a.eventDate) : +new Date(a.eventDate)-+new Date(b.eventDate));
  return <Page><section className="shell pt-16 md:pt-24 pb-10"><div className="eyebrow text-[#c44a2d] mb-4">Race directory / Find your next start</div><h1 className="display text-[clamp(74px,10vw,150px)]">THE STARTING<br/><span className="text-[#c44a2d]">LINEUP.</span></h1><p className="mt-7 max-w-lg text-[#526761]">Public races, live results, and the next chance to put your name on the board.</p></section><section className="shell pb-24"><div className="flex flex-col sm:flex-row gap-4 sm:items-center justify-between border-y border-[#173e3d]/20 py-5 mb-8"><div className="flex gap-2 flex-wrap">{['upcoming','past','all'].map(f => <button data-testid={`button-filter-${f}`} key={f} onClick={() => setFilter(f)} className={`px-4 py-2 eyebrow border rounded-sm transition-colors ${filter === f ? 'bg-[#173e3d] text-[#f6f0df] border-[#173e3d]' : 'border-[#173e3d]/20 hover:border-[#173e3d]'}`}>{f}</button>)}</div><label className="relative flex items-center"><Search size={17} className="absolute left-3 text-[#526761]"/><input data-testid="input-search-events" aria-label="Search races" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search race or city" className="field pl-10 sm:w-72"/></label></div>{events.isLoading ? <SkeletonRows/> : events.isError ? <InlineError error={events.error} retry={() => events.refetch()}/> : items.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{items.map((e,i)=><EventCard event={e} index={i} key={e.id}/>)}</div> : <StatePanel title={term ? 'No matching races.' : 'No races in this lane.'} detail={term ? 'Try a different search or clear your filters.' : 'Nothing scheduled here yet. Private invitation? Your code will get you in.'} action={<Link href="/join" className="btn btn-primary">Enter event code <ArrowRight size={16}/></Link>}/>}</section></Page>;
}
export function JoinPage() {
  const [,navigate] = useLocation(); const [code,setCode] = useState(''); const lookup = useJoinEventByCode();
  return <Page><section className="min-h-[70dvh] grid lg:grid-cols-2"><div className="bg-[#173e3d] text-[#f6f0df] p-8 md:p-16 lg:p-24 flex flex-col justify-between"><div className="eyebrow text-[#f8ba35]">Private race / By invitation</div><h1 className="display text-[clamp(70px,9vw,135px)] my-20">GOT THE<br/><span className="text-[#f8ba35]">CODE?</span><br/>GET IN.</h1><p className="max-w-sm text-[#f6f0df]/70">Some races are for the crew. Enter the code your host shared to find your start line.</p></div><div className="p-8 md:p-16 lg:p-24 flex items-center"><form className="w-full max-w-md" onSubmit={e=>{e.preventDefault(); lookup.mutate({data:{eventCode:code.trim().toUpperCase()}},{onSuccess:event=>navigate(`/events/${event.id}`)});}}><div className="eyebrow text-[#c44a2d] mb-4">01 / Find your event</div><h2 className="display text-5xl md:text-7xl mb-9">ENTER RACE CODE</h2><label className="field-label" htmlFor="race-code">Your invite code</label><input id="race-code" data-testid="input-event-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required placeholder="e.g. MILE2026" className="field mono text-lg uppercase mb-5"/>{lookup.isError && <div className="mb-5"><InlineError error={lookup.error}/></div>}<button data-testid="button-find-race" type="submit" disabled={lookup.isPending || !code.trim()} className="btn btn-primary w-full">{lookup.isPending ? 'Finding your race…' : 'Find my race'} <ArrowRight size={17}/></button><p className="text-xs text-[#68736b] mt-5">Need a public race instead? <Link href="/events" className="font-bold underline">Browse the lineup</Link>.</p></form></div></section></Page>;
}
export function EventDetailsPage() {
  const {id} = useParams<{id:string}>(); const eventId = Number(id); const valid = Number.isFinite(eventId) && eventId > 0;
  const event = useGetEvent(eventId,{query:{enabled:valid,queryKey:getGetEventQueryKey(eventId)}});
  const board = useGetLeaderboard(eventId,{query:{enabled:valid,queryKey:getGetLeaderboardQueryKey(eventId),refetchInterval:event.data?.status === 'active' ? 5000 : false}});
  const qc = useQueryClient(); const register = useCreateRegistration({mutation:{onSuccess:()=>{qc.invalidateQueries({queryKey:getListRegistrationsQueryKey(eventId)});qc.invalidateQueries({queryKey:getGetLeaderboardQueryKey(eventId)});}}});
  const [gender,setGender] = useState('all'); const [expanded,setExpanded] = useState<number|null>(null);
  const entries = (board.data || []).filter(e=>gender === 'all' || e.gender === gender).sort((a,b)=>Number(b.finished)-Number(a.finished) || b.lapCount-a.lapCount || a.totalElapsedMs-b.totalElapsedMs);
  if (!valid) return <Page><div className="shell py-24"><StatePanel title="That race isn't on the board." detail="Check the link and try again." action={<ArrowLink href="/events">Find races</ArrowLink>}/></div></Page>;
  if (event.isLoading) return <Page><div className="shell py-24"><SkeletonRows/></div></Page>;
  if (event.isError || !event.data) return <Page><div className="shell py-24"><StatePanel title="Race not found." detail="This event may have moved, or your connection may have dropped." action={<button className="btn btn-primary" onClick={()=>event.refetch()}>Try again</button>}/></div></Page>;
  const race = event.data;
  return <Page><section className="bg-[#173e3d] text-[#f6f0df] relative overflow-hidden"><div className="track-lines absolute inset-0 opacity-30"/><div className="shell relative pt-14 pb-16 md:pt-20 md:pb-24"><Link href="/events" className="eyebrow text-[#f8ba35] hover:underline">← All races</Link><div className="flex gap-3 items-center mt-12 mb-6"><span className={`eyebrow px-3 py-2 ${race.status==='active' ? 'bg-[#c44a2d]' : 'bg-[#f8ba35] text-[#173e3d]'}`}>{race.status==='active' ? '● LIVE RACE' : race.status}</span><span className="eyebrow opacity-60">RACE NO. {String(race.id).padStart(4,'0')}</span></div><h1 data-testid="text-event-title" className="display text-[clamp(72px,11vw,160px)] max-w-5xl">{race.title}</h1><div className="mt-10 flex flex-wrap gap-7 md:gap-12 text-sm font-bold"><span className="flex items-center gap-2"><Clock3 size={18} className="text-[#f8ba35]"/>{dateLabel(race.eventDate)} · {timeLabel(race.eventDate)}</span><span className="flex items-center gap-2"><MapPin size={18} className="text-[#f8ba35]"/>{race.locationName || 'Location to be announced'}</span><span className="flex items-center gap-2"><Users size={18} className="text-[#f8ba35]"/>{race.beerType || 'Beer details from host'}</span></div></div></section>
   <section className="shell py-14 md:py-20 grid lg:grid-cols-[1fr_340px] gap-12 lg:gap-16"><div><div className="eyebrow text-[#c44a2d] mb-4">The race / Details</div><h2 className="display text-5xl md:text-7xl mb-8">KNOW BEFORE<br/>YOU GO.</h2><div className="border-t border-[#173e3d]/20">{[['WHEN',`${dateLabel(race.eventDate)} at ${timeLabel(race.eventDate)}`],['WHERE',race.locationName || 'To be announced'],['WHAT’S POURING',race.beerType || 'Host to confirm'],['ENTRY',race.entryFee ? `$${race.entryFee}` : 'Check with host'],['EVENT CODE',race.eventCode]].map(([label,value])=><div key={label} className="grid grid-cols-[130px_1fr] gap-4 py-5 border-b border-[#173e3d]/20"><span className="eyebrow text-[#c44a2d]">{label}</span><span className="font-semibold" data-testid={`text-event-${label.toLowerCase().replaceAll(' ','-')}`}>{value}</span></div>)}</div>{race.prizesJson && race.prizesJson.length>0 && <div className="mt-12"><h3 className="display text-4xl mb-5">ON THE LINE</h3>{race.prizesJson.map((p,i)=><div key={i} className="flex gap-5 py-3 border-b border-[#173e3d]/20"><span className="mono text-[#c44a2d]">{String(p.position).padStart(2,'0')}</span><span>{p.description}</span></div>)}</div>}</div><aside className="lg:pt-4"><div className="bg-[#f8ba35] p-7 md:p-9 sticky top-5"><div className="eyebrow mb-6">Your place is waiting</div><Trophy size={35} strokeWidth={1.5}/><h3 className="display text-5xl mt-8 mb-4">GET ON<br/>THE LINE.</h3><p className="text-sm leading-relaxed mb-7">{race.status==='open' ? 'Register now and secure your spot on the starting line.' : race.status==='active' ? 'The race is underway. Follow the live board below.' : 'Registration is not currently open for this event.'}</p>{race.status === 'open' && <><Show when="signed-out"><Link href="/sign-in" className="btn btn-dark w-full">Sign in to register <ArrowRight size={16}/></Link></Show><Show when="signed-in"><button data-testid="button-register-event" disabled={register.isPending || register.isSuccess} onClick={()=>register.mutate({id:eventId})} className="btn btn-dark w-full">{register.isPending ? 'Securing your spot…' : register.isSuccess ? 'You’re on the list' : 'Register for race'} <ArrowRight size={16}/></button></Show></>}{register.isError && <div className="mt-4"><InlineError error={register.error}/></div>}{register.isSuccess && <p className="mt-4 text-xs font-bold">Registration received. Your host will confirm payment.</p>}{race.paymentInstructions && <div className="mt-6 pt-5 border-t border-[#173e3d]/30"><div className="eyebrow mb-2">Payment instructions</div><p className="text-sm whitespace-pre-line">{race.paymentInstructions}</p></div>}</div></aside></section>
  <section className="bg-[#e9dfc8] py-16 md:py-24"><div className="shell"><SectionHead kicker={race.status === 'active' ? 'Live timing / Updates every 5 seconds' : 'Race timing / The field'} title="THE BOARD." aside={race.status==='active' ? <span className="eyebrow flex items-center gap-2 text-[#c44a2d]"><Radio size={16}/> Live</span> : undefined}/><div className="flex gap-2 mb-6">{[['all','All runners'],['male','Men'],['female','Women'],['non_binary','Non-binary']].map(([value,label])=><button key={value} data-testid={`button-gender-${value}`} onClick={()=>setGender(value)} className={`eyebrow px-4 py-2 border ${gender===value ? 'bg-[#173e3d] text-[#f6f0df] border-[#173e3d]' : 'border-[#173e3d]/25'}`}>{label}</button>)}</div>{board.isLoading ? <SkeletonRows/> : board.isError ? <InlineError error={board.error} retry={()=>board.refetch()}/> : entries.length ? <div className="bg-[#f8f4e8] border border-[#173e3d]/15"><div className="hidden md:grid grid-cols-[70px_1fr_110px_110px_130px_25px] gap-4 px-6 py-4 eyebrow text-[#68736b] border-b border-[#173e3d]/20"><span>Rank</span><span>Runner</span><span>Laps</span><span>State</span><span>Time</span><span/></div>{entries.map((entry,i)=><div key={entry.registrationId}><button data-testid={`button-leaderboard-${entry.registrationId}`} className={`w-full text-left grid grid-cols-[45px_1fr_70px] md:grid-cols-[70px_1fr_110px_110px_130px_25px] gap-4 items-center px-5 md:px-6 py-5 border-b border-[#173e3d]/15 hover:bg-[#f8ba35]/20 transition-colors ${i===0?'bg-[#f8ba35]/15':''}`} onClick={()=>setExpanded(expanded===entry.registrationId?null:entry.registrationId)}><strong className="display text-3xl text-[#c44a2d]">{String(i+1).padStart(2,'0')}</strong><span className="font-bold truncate">{entry.preferredName || 'Runner'}</span><span className="mono text-xs">{entry.lapCount}/4</span><span className="eyebrow hidden md:block">{entry.finished?'Finished':'On course'}</span><span className="mono text-sm hidden md:block">{elapsed(entry.totalElapsedMs)}</span><ChevronDown size={16} className={`hidden md:block transition-transform ${expanded===entry.registrationId?'rotate-180':''}`}/></button>{expanded===entry.registrationId && <div className="px-6 py-5 bg-[#f1e9d6] border-b border-[#173e3d]/15"><div className="eyebrow mb-3">Splits / {entry.finished?'Finished':'On course'} · {elapsed(entry.totalElapsedMs)}</div><div className="flex gap-3 flex-wrap">{entry.laps.length ? entry.laps.map(l=><span key={l.lapNumber} className="mono text-xs px-3 py-2 bg-[#f8f4e8]">LAP {l.lapNumber} / {elapsed(l.splitTimeMs ?? l.elapsedMs)}</span>):<span className="text-sm">No splits recorded yet.</span>}</div></div>}</div>)}</div> : <StatePanel title="No times on the board. Yet." detail="When the first lap is logged, the race comes alive right here."/>}</div></section></Page>;
}